use pkm_rs::{Pkx, Species::*};

pub fn lookup_call_rate(pkx: &impl Pkx, is_usum: bool) -> u32 {
    match pkx.species_t() {
        Slowbro
            | Dhelmise
            | Drampa
            | Turtonator
            | Lurantis
            | Lycanroc
            | Relicanth
            | Glalie
            | Absol
            | Sharpedo
            | Miltank
            | Lapras
            | Gyarados
            | Tauros
            | Pinsir
            | Scyther
            | Kangaskhan
            | Marowak => 3,
        Raticate
            | HakamoO
            | Bruxish
            | Pyukumuku
            | Palossand
            | Steenee
            | Bewear
            | Shiinotic
            | Araquanid
            | Mudsdale
            | Ribombee
            | Oricorio
            | Gumshoos
            | Klefki
            | Fletchinder
            | Mandibuzz
            | Braviary
            | Alomomola
            | Garbodor
            | Krokorok
            | Boldore
            | Herdier
            | Lumineon
            | Munchlax
            | Drifblim
            | Gastrodon
            | Metang
            | Shelgon
            | Luvdisc
            | Whiscash
            | Vibrava
            | Spinda
            | Torkoal
            | Wailord
            | Hariyama
            | Masquerain
            | Pelipper
            | Skarmory
            | Granbull
            | Lanturn
            | Ariados
            | Ledian
            | Dragonair
            | Magmar
            | Electabuzz
            | Seaking
            | Hypno
            | Haunter
            | Muk
            | Magneton
            | Graveler
            | Tentacruel
            | Machoke
            | Kadabra
            | Poliwhirl
            | Primeape
            | Golduck
            | Persian
            | Dugtrio
            | Parasect
            | Jigglypuff
            | Clefairy
            | Pikachu
            | Fearow => 6,
        Rattata
            | JangmoO
            | Mimikyu
            | Togedemaru
            | Sandygast
            | Comfey
            | Bounsweet
            | Stufful
            | Salandit
            | Morelull
            | Fomantis
            | Dewpider
            | Mudbray
            | Wishiwashi
            | Rockruff
            | Cutiefly
            | Crabrawler
            | Grubbin
            | Yungoos
            | Trumbeak
            | Phantump
            | Carbink
            | Pancham
            | Fletchling
            | Vullaby
            | Rufflet
            | Emolga
            | Trubbish
            | Sandile
            | Petilil
            | Cottonee
            | Roggenrola
            | Lillipup
            | Finneon
            | Drifloon
            | Shellos
            | Beldum
            | Bagon
            | Snorunt
            | Feebas
            | Barboach
            | Trapinch
            | Wailmer
            | Carvanha
            | Nosepass
            | Makuhita
            | Surskit
            | Wingull
            | Smeargle
            | Delibird
            | Corsola
            | Sneasel
            | Snubbull
            | Misdreavus
            | Murkrow
            | Chinchou
            | Spinarak
            | Ledyba
            | Dratini
            | Eevee
            | Ditto
            | Magikarp
            | Staryu
            | Goldeen
            | Drowzee
            | Gastly
            | Shellder
            | Grimer
            | Magnemite
            | Slowpoke
            | Geodude
            | Machop
            | Abra
            | Poliwag
            | Growlithe
            | Mankey
            | Meowth
            | Diglett
            | Paras
            | Golbat
            | Vulpix
            | Sandshrew
            | Spearow => 9,
        Caterpie
            | Passimian
            | Oranguru
            | Salazzle
            | Charjabug
            | Pikipek
            | Riolu
            | Bonsly
            | Magby
            | Elekid
            | Igglybuff
            | Cleffa
            | Pichu
            | Cubone
            | Exeggcute
            | Tentacool
            | Psyduck
            | Zubat
            | Metapod => 15,
        Lickitung
            | Hawlucha
            | Larvesta
            | Druddigon
            | Mienshao
            | Tropius
            | Remoraid
            | Heracross
            | Dunsparce => if is_usum { 3 } else { 0 },
        Arbok
            | Noivern
            | Clawitzer
            | Dragalge
            | Malamar
            | Furfrou
            | Pyroar
            | Mienfoo
            | Jellicent
            | Zoroark
            | Scrafty
            | Lopunny
            | Banette
            | Crawdaunt
            | Manectric
            | Mawile
            | Houndoom
            | Forretress
            | Flaaffy
            | Xatu
            | Noctowl
            | Dewgong => if is_usum { 6 } else { 0 },
        Chansey
            | Noibat
            | Dedenne
            | Clauncher
            | Skrelp
            | Inkay
            | Floette // Warn: Apparently Only red Floette can call SOS
            | Litleo
            | Frillish
            | Minccino
            | Zorua
            | Scraggy
            | Basculin
            | Buneary
            | Shuppet
            | Kecleon
            | Corphish
            | Electrike
            | Pupitar
            | Larvitar
            | Houndour
            | Pineco
            | Aipom
            | Mareep
            | Natu
            | Hoothoot
            | Seel
            | Ekans => if is_usum { 9 } else { 0 },
        Smoochum
            | Flabebe
            | Bisharp
            | Golurk
            | Golett
            | Beheeyem
            | Elgyem
            | Mantyke
            | MimeJr
            | Clamperl
            | Claydol
            | Baltoy => if is_usum { 15 } else { 0 },
        _ => 0,
    }
}
