name: Lint, Test, Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  lint-build-deploy:
    name: Lint, test, and build
    runs-on: ubuntu-latest
    container: zaksabeast/devkit3ds-rust
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build PokeReader
        run: make release

      - name: Build Launcher
        run: make -C launcher

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PokeReader
          retention-days: 5
          path: |
            out/release/pkrd.cia
            launcher/out/pkrd-launcher.cia
            launcher/out/pkrd-launcher.3dsx

      - name: Draft release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            out/release/pkrd.cia
            launcher/out/pkrd-launcher.cia
            launcher/out/pkrd-launcher.3dsx
